// ============================================
// MAZU - Data Layer
// ============================================

const SITE_DATA = {
  company: {
    name: 'MAZU',
    slogan: 'Seating the World with Excellence',
    founded: 2010,
    location: 'Tianjin, China',
    employees: '500+',
    annualOutput: '2M+',
    countries: '50+',
  },

  categories: [
    {
      id: 'plastic-folding-chair',
      name: 'Plastic Folding Chair',
      slug: 'plastic-folding-chair',
      desc: 'Lightweight, durable, and weather-resistant folding seating solutions',
      image: 'plastic-folding-chair.png',
    },
    {
      id: 'metal-folding-chair',
      name: 'Metal Folding Chair',
      slug: 'metal-folding-chair',
      desc: 'Industrial-strength folding chairs for heavy-duty use',
      image: 'metal-folding-chair.jpg',
    },
    {
      id: 'upholstered-folding-chair',
      name: 'Upholstered Folding Chair',
      slug: 'upholstered-folding-chair',
      desc: 'Premium cushioned folding seating for comfort and elegance',
      image: 'upholstered-folding-chair.png',
    },
    {
      id: 'outdoor-folding-chair',
      name: 'Outdoor Folding Chair',
      slug: 'outdoor-folding-chair',
      desc: 'UV-stabilized and weatherproof folding chairs for outdoor events and leisure',
      image: 'outdoor-folding-chair.jpg',
    },
    {
      id: 'folding-stool',
      name: 'Folding Stool',
      slug: 'folding-stool',
      desc: 'Compact, stackable folding stools for events, bars, and everyday use',
      image: 'folding-stool.png',
    },
  ],

  products: [
    // Plastic Folding Chairs
    {
      id: 'p-001',
      sku: 'MZ-PL-001',
      name: 'AeroLite White Folding Chair',
      category: 'plastic-folding-chair',
      categoryName: 'Plastic Folding Chair',
      badge: 'New',
      description: 'Ultra-lightweight polypropylene folding chair with ergonomic contoured design. Perfect for outdoor events, banquet halls, and rental businesses.',
      image: 'MZ-PL-001.png',
      images: ['MZ-PL-001.png','MZ-PL-001.png','MZ-PL-001.png','MZ-PL-001.png'],
      dimensions: '450 × 500 × 800 mm',
      weight: 3.2,
      packingDimensions: '980 × 480 × 480 mm (50 pcs/ctn)',
      packingWeight: 165,
      materials: 'PP Plastic, Steel Tube',
      deliveryTime: '15-20 days',
      containerLoading: '5,400 pcs / 20ft; 11,200 pcs / 40HQ',
      moq: '200 pcs',
      warranty: '2 years',
    },
    {
      id: 'p-002',
      sku: 'MZ-PL-002',
      name: 'VivaPro Red Event Chair',
      category: 'plastic-folding-chair',
      categoryName: 'Plastic Folding Chair',
      badge: 'Popular',
      description: 'High-impact resin folding chair in vibrant red. UV-stabilized for outdoor use, with a weight capacity of 250 kg.',
      image: 'MZ-PL-002.png',
      images: [
        'MZ-PL-002.png',
        'MZ-PL-003.png',
        'MZ-PL-004.png',
        'MZ-PL-005.png',
      ],
      dimensions: '460 × 520 × 810 mm',
      weight: 3.5,
      packingDimensions: '990 × 490 × 490 mm (48 pcs/ctn)',
      packingWeight: 172,
      materials: 'HDPE Plastic, Powder-coated Steel',
      deliveryTime: '15-20 days',
      containerLoading: '5,200 pcs / 20ft; 10,800 pcs / 40HQ',
      moq: '200 pcs',
      warranty: '2 years',
    },
    {
      id: 'p-003',
      sku: 'MZ-PL-003',
      name: 'EcoStack Armless Chair',
      category: 'plastic-folding-chair',
      categoryName: 'Plastic Folding Chair',
      description: 'Stackable armless folding chair made from 100% recycled plastic. Certified eco-friendly for sustainable procurement.',
      image: 'MZ-PL-003.png',
      images: [
        'MZ-PL-003.png',
        'MZ-PL-006.png',
        'MZ-PL-007.png',
        'MZ-PL-008.png',
      ],
      dimensions: '440 × 490 × 790 mm',
      weight: 2.9,
      packingDimensions: '970 × 470 × 470 mm (55 pcs/ctn)',
      packingWeight: 163,
      materials: 'Recycled PP Plastic, Galvanized Steel',
      deliveryTime: '20-25 days',
      containerLoading: '5,800 pcs / 20ft; 12,000 pcs / 40HQ',
      moq: '300 pcs',
      warranty: '2 years',
    },
    // Metal Folding Chairs
    {
      id: 'p-004',
      sku: 'MZ-MT-001',
      name: 'IronClad Heavy-Duty Chair',
      category: 'metal-folding-chair',
      categoryName: 'Metal Folding Chair',
      badge: 'Best Seller',
      description: 'Commercial-grade steel frame folding chair with reinforced cross-bracing. Designed for high-traffic venues and rental fleets.',
      image: 'MZ-MT-001.jpg',
      images: [
        'MZ-MT-001.jpg',
        'MZ-MT-002.jpg',
        'MZ-MT-003.jpg',
        'MZ-MT-004.jpg',
      ],
      dimensions: '470 × 520 × 830 mm',
      weight: 4.8,
      packingDimensions: '1000 × 500 × 500 mm (40 pcs/ctn)',
      packingWeight: 198,
      materials: 'Q195 Steel Tube, Textilene Mesh',
      deliveryTime: '18-23 days',
      containerLoading: '3,800 pcs / 20ft; 8,000 pcs / 40HQ',
      moq: '100 pcs',
      warranty: '3 years',
    },
    {
      id: 'p-005',
      sku: 'MZ-MT-002',
      name: 'UrbanMesh Black Frame Chair',
      category: 'metal-folding-chair',
      categoryName: 'Metal Folding Chair',
      description: 'Sleek matte-black metal frame with breathable mesh seat and back. Modern aesthetic for cafes, co-working spaces, and events.',
      image: 'MZ-MT-002.jpg',
      images: [
        'MZ-MT-002.jpg',
        'MZ-MT-005.jpg',
        'MZ-MT-006.jpg',
        'MZ-MT-007.jpg',
      ],
      dimensions: '460 × 510 × 820 mm',
      weight: 4.2,
      packingDimensions: '990 × 490 × 490 mm (45 pcs/ctn)',
      packingWeight: 195,
      materials: 'Powder-coated Steel, PVC-coated Polyester Mesh',
      deliveryTime: '15-20 days',
      containerLoading: '4,200 pcs / 20ft; 8,800 pcs / 40HQ',
      moq: '150 pcs',
      warranty: '2 years',
    },
    // Upholstered Folding Chairs
    {
      id: 'p-006',
      sku: 'MZ-UP-001',
      name: 'VelvetLux Padded Banquet Chair',
      category: 'upholstered-folding-chair',
      categoryName: 'Upholstered Folding Chair',
      badge: 'Premium',
      description: 'Luxurious velvet-upholstered folding chair with high-density foam cushioning. Ideal for weddings, galas, and upscale events.',
      image: 'MZ-UP-001.png',
      images: [
        'MZ-UP-001.png',
        'MZ-UP-002.png',
        'MZ-UP-003.png',
        'MZ-UP-004.png',
      ],
      dimensions: '480 × 550 × 860 mm',
      weight: 6.5,
      packingDimensions: '1020 × 530 × 530 mm (25 pcs/ctn)',
      packingWeight: 170,
      materials: 'Velvet Fabric, 40D High-density Foam, Steel Frame',
      deliveryTime: '20-25 days',
      containerLoading: '2,400 pcs / 20ft; 5,000 pcs / 40HQ',
      moq: '100 pcs',
      warranty: '2 years',
    },
    {
      id: 'p-007',
      sku: 'MZ-UP-002',
      name: 'ComfortWeave Gray Cushion Chair',
      category: 'upholstered-folding-chair',
      categoryName: 'Upholstered Folding Chair',
      description: 'Premium fabric-upholstered folding chair with medium-firm cushion. Stain-resistant treatment for commercial use.',
      image: 'MZ-UP-002.png',
      images: [
        'MZ-UP-002.png',
        'MZ-UP-005.png',
        'MZ-UP-006.png',
        'MZ-UP-007.png',
      ],
      dimensions: '470 × 540 × 850 mm',
      weight: 5.8,
      packingDimensions: '1010 × 520 × 520 mm (28 pcs/ctn)',
      packingWeight: 168,
      materials: 'Linen-blend Fabric, 35D Foam, Steel Tube',
      deliveryTime: '18-23 days',
      containerLoading: '2,700 pcs / 20ft; 5,600 pcs / 40HQ',
      moq: '120 pcs',
      warranty: '2 years',
    },
    // Outdoor Folding Chairs
    {
      id: 'p-008',
      sku: 'MZ-OD-001',
      name: 'VivaPro Red Event Chair',
      category: 'outdoor-folding-chair',
      categoryName: 'Outdoor Folding Chair',
      badge: 'New',
      description: 'High-impact resin folding chair in vibrant red. UV-stabilized for outdoor use, with a weight capacity of 250 kg. Ideal for concerts, sports events, and outdoor weddings.',
      image: 'MZ-OD-001.jpg',
      images: [
        'MZ-OD-001.jpg',
        'MZ-OD-003.jpg',
        'MZ-OD-004.jpg',
        'MZ-OD-005.jpg',
      ],
      dimensions: '460 × 520 × 810 mm',
      weight: 3.5,
      packingDimensions: '990 × 490 × 490 mm (48 pcs/ctn)',
      packingWeight: 172,
      materials: 'UV-stabilized HDPE, Powder-coated Steel',
      deliveryTime: '15-20 days',
      containerLoading: '5,200 pcs / 20ft; 10,800 pcs / 40HQ',
      moq: '200 pcs',
      warranty: '2 years',
    },
    {
      id: 'p-009',
      sku: 'MZ-OD-002',
      name: 'SunGuard Beach Folding Chair',
      category: 'outdoor-folding-chair',
      categoryName: 'Outdoor Folding Chair',
      description: 'Lightweight folding chair designed for beaches, camping, and outdoor leisure. Rust-resistant frame and quick-dry fabric.',
      image: 'MZ-OD-002.jpg',
      images: ['MZ-OD-002.jpg','MZ-OD-002.jpg','MZ-OD-002.jpg','MZ-OD-002.jpg'],
      dimensions: '520 × 500 × 800 mm',
      weight: 2.8,
      packingDimensions: '980 × 510 × 200 mm (20 pcs/ctn)',
      packingWeight: 62,
      materials: '600D Oxford Fabric, Aluminum Frame',
      deliveryTime: '18-23 days',
      containerLoading: '3,600 pcs / 20ft; 7,500 pcs / 40HQ',
      moq: '200 pcs',
      warranty: '2 years',
    },
    // Folding Stools
    {
      id: 'p-010',
      sku: 'MZ-ST-001',
      name: 'PureTop 6ft Folding Stool',
      category: 'folding-stool',
      categoryName: 'Folding Stool',
      badge: 'Best Seller',
      description: 'Heavy-duty 6-foot folding stool with HDPE top and steel frame. Weather-resistant for indoor and outdoor use.',
      image: 'MZ-ST-001.png',
      images: ['MZ-ST-001.png','MZ-ST-001.png','MZ-ST-001.png','MZ-ST-001.png'],
      dimensions: '1830 × 760 × 740 mm',
      weight: 12.8,
      packingDimensions: '920 × 770 × 90 mm (1 pc/ctn)',
      packingWeight: 14,
      materials: 'HDPE Tabletop, Powder-coated Steel Frame',
      deliveryTime: '15-20 days',
      containerLoading: '360 pcs / 20ft; 760 pcs / 40HQ',
      moq: '50 pcs',
      warranty: '3 years',
    },
    {
      id: 'p-011',
      sku: 'MZ-ST-002',
      name: 'RoundBanquet 5ft Stool',
      category: 'folding-stool',
      categoryName: 'Folding Stool',
      description: 'Round folding banquet stool with 5ft diameter. Seats 8 people comfortably. Ideal for weddings, banquets, and catering events.',
      image: 'MZ-ST-002.png',
      images: ['MZ-ST-002.png','MZ-ST-002.png','MZ-ST-002.png','MZ-ST-002.png'],
      dimensions: '1520 × 1520 × 740 mm',
      weight: 15.5,
      packingDimensions: '1540 × 770 × 90 mm (1 pc/ctn)',
      packingWeight: 17,
      materials: 'PVC Laminated Plywood, Steel Frame, Edge Banding',
      deliveryTime: '18-23 days',
      containerLoading: '250 pcs / 20ft; 520 pcs / 40HQ',
      moq: '30 pcs',
      warranty: '2 years',
    },
    {
      id: 'p-012',
      sku: 'MZ-ST-003',
      name: 'MiniCamp 4ft Bi-fold Stool',
      category: 'folding-stool',
      categoryName: 'Folding Stool',
      badge: 'New',
      description: 'Compact 4ft bi-fold folding stool with carry handle. Lightweight and portable for trade shows, markets, and outdoor activities.',
      image: 'MZ-ST-003.png',
      images: ['MZ-ST-003.png','MZ-ST-003.png','MZ-ST-003.png','MZ-ST-003.png'],
      dimensions: '1220 × 610 × 740 mm',
      weight: 8.5,
      packingDimensions: '620 × 620 × 90 mm (1 pc/ctn)',
      packingWeight: 9.5,
      materials: 'HDPE Tabletop, Aluminum Frame',
      deliveryTime: '15-20 days',
      containerLoading: '720 pcs / 20ft; 1,500 pcs / 40HQ',
      moq: '100 pcs',
      warranty: '2 years',
    },
  ],

  advantages: [
    {
      icon: 'factory',
      title: 'Factory-Direct Pricing',
      desc: 'No middlemen. Buy straight from our Tianjin factory for the best landed cost and transparent pricing.',
    },
    {
      icon: 'capacity',
      title: 'Massive Capacity',
      desc: 'Over 20,000 pieces produced every day across a 50,000 m² production facility with automated lines.',
    },
    {
      icon: 'delivery',
      title: 'Reliable Lead Times',
      desc: 'Standard orders ship in 15–25 days, with dedicated production lines for high-volume contracts.',
    },
    {
      icon: 'design',
      title: 'Design & Material R&D',
      desc: 'In-house designers and material labs developing durable, modern furniture with the latest materials.',
    },
    {
      icon: 'quality',
      title: 'Certified Quality',
      desc: 'ISO 9001 certified with full QC from raw pellets to palletized export. Every batch fully inspected.',
    },
    {
      icon: 'global',
      title: 'Global Service',
      desc: 'Multilingual sales and logistics support across Europe, the Middle East, and the Americas.',
    },
  ],

  partners: [
    'Decathlon', 'IKEA', 'Walmart', 'Carrefour', 'Lidl', 'Aldi',
    'Staples', 'Office Depot', 'Coca-Cola', 'PepsiCo', 'Marriott', 'Hilton',
  ],

  markets: [
    { region: 'Europe', countries: '25+ countries', flag: '🇪🇺' },
    { region: 'Middle East', countries: '12+ countries', flag: '🇦🇪' },
    { region: 'Americas', countries: '15+ countries', flag: '🇺🇸' },
  ],

  faqs: [
    {
      q: 'What is your minimum order quantity (MOQ)?',
      a: 'Our standard MOQ is 100 pieces per model. For first-time clients, we can offer a lower trial MOQ of 50 pieces for selected models. Mixed-container orders with multiple SKUs are also welcome — contact our sales team for a customized quote.',
    },
    {
      q: 'How long does production and delivery take?',
      a: 'Standard orders typically ship within 15–25 days depending on the model and quantity. Large-volume or custom orders may take 25–35 days. Sea freight to European ports takes approximately 28–35 days, while Middle East destinations take 15–20 days. We provide full tracking and regular updates.',
    },
    {
      q: 'Can I customize the product — colors, logo, materials?',
      a: 'Absolutely. We offer extensive customization including custom colors (Pantone matching), logo printing/embroidery, custom fabric/material selection, and even full product development from your sketches or samples. Our R&D team handles everything from prototyping to tooling. MOQ for custom models starts at 500 pieces.',
    },
    {
      q: 'What certifications do you have?',
      a: 'MAZU is ISO 9001:2015 certified. Our products comply with EN 16139 (strength and durability), REACH (EU chemical regulation), and BIFMA X5.1 standards. We can provide test reports and certification documents upon request. Specific market certifications (e.g., SGS, TÜV) are available for premium models.',
    },
    {
      q: 'How do you handle quality control?',
      a: 'We implement a 3-step QC process: raw material inspection upon arrival, in-line quality checks during production, and 100% final inspection before packaging. Our QC team of 30+ inspectors monitors every production line. We welcome third-party inspections (SGS, Intertek, etc.) at the client\'s request.',
    },
    {
      q: 'What payment terms do you accept?',
      a: 'We accept T/T (30% deposit, 70% before shipment), L/C at sight, and for established clients, O/A 30–60 days. New clients start with T/T terms. All payments are processed through our verified company bank account. We do not accept personal payment methods.',
    },
    {
      q: 'Do you provide samples? How long does it take?',
      a: 'Yes, we provide samples. Standard samples are typically ready in 3–5 working days. Custom samples (with logo or color changes) take 7–10 working days. Sample fees are charged upfront but are fully refundable upon placing a bulk order. We ship samples via DHL, FedEx, or your preferred courier.',
    },
    {
      q: 'What warranty do you offer?',
      a: 'We offer a 2-year standard warranty on all folding chairs against manufacturing defects, and 3 years on premium metal-framed models. Warranty covers structural integrity, frame welding, and hardware. Normal wear and tear, misuse, or damage from improper assembly are not covered. We stand behind our products and provide replacement parts if needed.',
    },
  ],

  timeline: [
    { year: '2010', title: 'Founded in Hebei', desc: 'Started as a small folding-chair workshop serving local and regional markets.' },
    { year: '2014', title: 'Product line expanded', desc: 'Added tables and office chairs; the team grew past 200 employees.' },
    { year: '2018', title: 'Certified and exporting', desc: 'Achieved ISO 9001 and shipped our first containers to Europe and the Middle East.' },
    { year: '2022', title: 'Global scale', desc: 'Annual output surpassed 2 million units, serving 50+ countries worldwide.' },
    { year: '2026', title: 'Building what is next', desc: 'Investing in sustainable materials and global R&D for the decade ahead.' },
  ],

  values: [
    { icon: 'I', title: 'Integrity', desc: 'We build every partnership on honesty, transparency, and keeping our word.' },
    { icon: 'Q', title: 'Quality', desc: 'Rigorous standards at every step, from raw material to finished product.' },
    { icon: 'In', title: 'Innovation', desc: 'Continuous R&D in design, materials, and manufacturing efficiency.' },
    { icon: 'P', title: 'Partnership', desc: 'Your success is our success. We grow together with the clients we serve.' },
  ],

  cases: [
    {
      id: 'c-001',
      tag: 'Hospitality',
      title: 'Hilton Hotel Chain — 5,000 Chair Supply',
      desc: 'Supplied premium banquet chairs across 12 Hilton properties in the Middle East with custom embroidery.',
      image: 'conference-room.png',
    },
    {
      id: 'c-002',
      tag: 'Retail',
      title: 'Decathlon Exclusive Outdoor Range',
      desc: 'Co-developed a line of outdoor folding chairs for Decathlon\'s 200+ European stores.',
      image: 'case-retail.png',
    },
    {
      id: 'c-003',
      tag: 'Events',
      title: 'Dubai Expo 2025 Seating Solution',
      desc: 'Delivered 8,000 folding chairs and 1,200 tables for the Dubai World Expo venues.',
      image: 'case-event.png',
    },
    {
      id: 'c-004',
      tag: 'Office',
      title: 'WeWork — Training Room Furniture',
      desc: 'Furnished 35 WeWork locations across Europe with ergonomic folding training chairs.',
      image: 'case-restaurant.png',
    },
    {
      id: 'c-005',
      tag: 'Education',
      title: 'UAE Ministry of Education',
      desc: 'Supplied 12,000 school folding chairs across 80 educational institutions in the UAE.',
      image: 'case-office.png',
    },
    {
      id: 'c-006',
      tag: 'Retail',
      title: 'Carrefour Private Label Program',
      desc: 'Developed and manufactured a private-label folding furniture range for Carrefour Middle East.',
      image: 'case-school.png',
    },
  ],

  blogPosts: [
    {
      id: 'b-001',
      title: 'How to Choose the Right Folding Chairs for Your Event Rental Business',
      category: 'Guide',
      date: 'August 15, 2026',
      excerpt: 'A comprehensive guide to selecting folding chairs that balance durability, aesthetics, and ROI for rental companies.',
      image: 'conference-room.png',
      featured: true,
    },
    {
      id: 'b-002',
      title: 'Sustainable Materials in Folding Furniture: What Buyers Need to Know',
      category: 'Industry',
      date: 'August 8, 2026',
      excerpt: 'Exploring recycled plastics, FSC wood, and other eco-friendly materials reshaping the folding furniture industry.',
      image: 'blog-shipping.png',
    },
    {
      id: 'b-003',
      title: '5 Ways to Reduce Shipping Costs for Bulk Furniture Orders',
      category: 'Tips',
      date: 'July 28, 2026',
      excerpt: 'Smart container loading, product design optimization, and logistics strategies to lower your landed cost.',
      image: 'warehouse.png',
    },
    {
      id: 'b-004',
      title: 'Quality Control in Chinese Furniture Manufacturing: A Deep Dive',
      category: 'Industry',
      date: 'July 15, 2026',
      excerpt: 'An inside look at MAZU\'s 3-step quality control process from raw material inspection to final export.',
      image: 'factory-interior.png',
    },
    {
      id: 'b-005',
      title: 'Trends in Commercial Seating: What Hotels and Venues Want in 2026',
      category: 'Trends',
      date: 'July 1, 2026',
      excerpt: 'From minimalist design to sustainability, discover the key trends driving commercial seating purchases this year.',
      image: 'chair-collection.png',
    },
    {
      id: 'b-006',
      title: 'MAZU Launches New Eco-Line of Recycled Plastic Chairs',
      category: 'News',
      date: 'June 20, 2026',
      excerpt: 'Introducing our latest collection of eco-friendly folding chairs made from 100% recycled polypropylene.',
      image: 'case-retail.png',
    },
  ],
};
